### ISSUE TITLE
Не билдится(

### ISSUE THREAD

**Issue by TheMerret** [inigomontoya722/diasurazov_homework_react#1]
![image](https://github.com/inigomontoya722/diasurazov_homework_react/assets/88326901/c1220535-33b3-46b4-9fca-ebef56321b2f)

**Comment by inigomontoya722** [comment]
Так я походу не то что-то на гитхаб залил. Так как у меня все билдится и другой проверяющий уже оценил

**Comment by inigomontoya722** [comment]
Мб какие то правки внес и забыл

**Comment by inigomontoya722** [comment]
То что на яндекс диске не получиться проверить?
